apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-server
spec:
  serviceName: "minecraft"
  replicas: 1 # Scaling out requires proxies like Velocity/Waterfall, keeping 1 for standalone demo
  selector:
    matchLabels:
      app: mc-server
  template:
    metadata:
      labels:
        app: mc-server
    spec:
      containers:
      - name: mc
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        - name: MODPACK_PLATFORM
          value: "AUTO_CURSEFORGE"
        - name: CF_SLUG
          value: "all-the-mods-gravitas2"
        ports:
        - containerPort: 25565
          name: mc-port
        volumeMounts:
        - name: mc-data
          mountPath: /data
      volumes:
      - name: mc-data
        persistentVolumeClaim:
          claimName: mc-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
  selector:
    app: mc-server
